### ISSUE TITLE
link bootstrap

### ISSUE THREAD

**Issue by cindylopez1814** [cindylopez1814/scl-2018-05-bc-core-am-datadashboard#1]
Chicas estan listos los links en el html para poder maquetear.
Recuerden dejar los comentarios para no perdernos 👍 ❤️

**Comment by LeslieInostroza** [comment]
gracias cindy, hay que empezar a ver el js :O vamos co todo :100:

**Comment by LeslieInostroza** [comment]
acabo de sicronizarme  ocn los ultims cambios, agregando el menu :)

**Comment by LeslieInostroza** [comment]
acabo de hacer un pequeño cambio :)
