### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by MarciaMillanao** [cindylopez1814/scl-2018-05-bc-core-am-datadashboard#8]
Hola chicas!
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- El link de css tiene un / al final que no va.

2.- En HTML el primer div class container-fluid, la clase esta mal escrita, con mayúscula.

3.- Les recomiendo usar nombre de identificadores (variables en js, clases o id en html & css) bien descriptivos y en inglés.

4.- Usen los issues para coordinarse y comunicarse entre ustedes.

5.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía [https://www.youtube.com/watch?v=9SZSHGA95x4](url)
[https://www.youtube.com/watch?v=nI5VdsVl0FM](url) .

6.- Revisen bien su planificación, ven los tiempos de entrega, aún no han comenzado a desarrollar código en js

Vamos con todo!!!!

**Comment by cindylopez1814** [comment]
Gracias Marcia revisaremos esos puntos, ya estamos trabajando en JS... gracias por el apoyo.

**Comment by LeslieInostroza** [comment]
Gracias marcia por el feedback, revisaremos todos esos puntos :3

**Comment by JessicaNH** [comment]
gracias!...estamos en esos detalles.
